force-app/main/default/objects/Car__c/fields/Production_Start__c.field-meta.xml
<CustomField>
    <fullName>Production_Start__c</fullName>
    <label>Production Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Info__c/Manufacturing_Info__c.object-meta.xml
<CustomObject>
    <label>Manufacturing Info</label>
    <nameField>
        <label>Manufacturing Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturing Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manufacturing_Info__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Manufacturing Info</relationshipLabel>
    <relationshipName>Manufacturing_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Info__c/fields/Manufacturing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Start_Date__c</fullName>
    <label>Manufacturing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/manufacturingInfoTriggerHandler.cls
public with sharing class manufacturingInfoTriggerHandler {
    public static void handleInsertrigger(List<Manufacturing_Info__c> newTrigger){
        List<Car__c> newCars = new List<Car__c>();
        Map<Id,Manufacturing_Info__c> cars2Update = new Map<Id,Manufacturing_Info__c>();
        Map<Manufacturing_Info__c, Car__c> MIToCar = new Map<Manufacturing_Info__c, Car__c>();
        for(Manufacturing_Info__c MI:newTrigger){
            if(MI.car__c == null){
                Car__c newCar = new Car__c(
                    name='default name', 
                    production_start__c=MI.manufacturing_start_date__c
                    );
                newCars.add(newCar);
                MIToCar.put(MI, newCar);
            }else{
                cars2Update.put(MI.Car__c, MI);
            }
        }
        insert newCars;
        for(Manufacturing_Info__c MI:MIToCar.keySet()){
            MI.car__c = MIToCar.get(MI).Id;
        }
        List<Car__c> cars = [SELECT Id, production_start__c FROM Car__c WHERE Id IN :cars2Update.keySet()];
        for(Car__c c:cars){
            Manufacturing_Info__c MI = cars2Update.get(c.Id);
            c.production_start__c = MI.manufacturing_start_date__c;
        }
        update cars;
    }

    public static void handleUpdateTrigger(List<Manufacturing_Info__c> newTrigger, Map<Id, Manufacturing_Info__c> oldMap){
        List<Manufacturing_Info__c> MI2Update = new List<Manufacturing_Info__c>();
        for(Manufacturing_Info__c MI : newTrigger){
            if(oldMap.get(MI.Id).manufacturing_start_date__c != MI.manufacturing_start_date__c){
                MI2Update.add(MI);
            }
        }
        Map<Id,Manufacturing_Info__c> cars2Update = new Map<Id,Manufacturing_Info__c>();
        for(Manufacturing_Info__c MI:MI2Update){
            cars2Update.put(MI.Car__c, MI);
        }
        List<Car__c> cars = [SELECT Id, production_start__c FROM Car__c WHERE Id IN :cars2Update.keySet()];
        for(Car__c c:cars){
            Manufacturing_Info__c MI = cars2Update.get(c.Id);
            c.production_start__c = MI.manufacturing_start_date__c;
        }
        update cars;
    }
    
}