force-app/main/default/objects/Car__c/fields/Production_Start__c.field-meta.xml
<CustomField>
    <fullName>Production_Start__c</fullName>
    <label>Production Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Info__c/Manufacturing_Info__c.object-meta.xml
<CustomObject>
    <label>Manufacturing Info</label>
    <nameField>
        <label>Manufacturing Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturing Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manufacturing_Info__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Manufacturing Info</relationshipLabel>
    <relationshipName>Manufacturing_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Info__c/fields/Manufacturing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Start_Date__c</fullName>
    <label>Manufacturing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/carTriggerHandler.cls
public with sharing class carTriggerHandler {
    public static void handleInserTrigger(List<Car__c> newTrigger){
        List<Manufacturing_Info__c> newMI = new List<Manufacturing_Info__c>();
        for(Car__c car:newTrigger){
            newMI.add(new Manufacturing_Info__c(
                name='default name', 
                manufacturing_start_date__c=car.production_start__c, 
                car__c=car.Id
                ));
        }
        insert newMI;
    }

    public static void handleUpdateTrigger(Map<Id, Car__c> newMap, List<Car__c> oldTrigger){
        List<Car__c> Car2Update = new List<Car__c>();
        for(Car__c c : oldTrigger){
            if(newMap.get(c.Id).production_start__c != c.production_start__c){
                Car2Update.add(c);
            }
        }
        List<Car__c> MI2Update = [SELECT Id, (SELECT Id, Manufacturing_Start_Date__c FROM Manufacturing_Info__r)
                                 FROM Car__c WHERE Id IN :oldTrigger];
        List<Manufacturing_Info__c> MIs = new List<Manufacturing_Info__c>();
        for(Car__c c:MI2Update){
            for(Manufacturing_Info__c MI:c.Manufacturing_Info__r){
                MI.manufacturing_start_date__c = newMap.get(c.Id).production_start__c;
                MIs.add(MI);
            }
        }
        update MIs;
    }
}